apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-web-service
spec:
  type: NodePort
  selector:
    app: dotnet-app-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001