apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-web-service
spec:
  type: NodePort
  selector:
    app: dotnet-app-web
  ports:
    - name: "http"
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
    - name: "https"
      protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001