name: my_webapi_app_db
version: "3.8"
services:
  webapi:
    container_name: my_webapi_app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=MyDatabase;User Id=sa;Password=YourStrongPassword!;TrustServerCertificate=True;MultipleActiveResultSets=true"
    depends_on:
      - db
    networks:
      - app_network
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: my_webapi_app_db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrongPassword!"
    ports:
      - "1433:1433"
    networks:
      - app_network
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./backups:/var/opt/mssql/backup
  backup:
    image: mcr.microsoft.com/mssql-tools
    container_name: sql-server-backup
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - ./backups:/var/opt/mssql/backup
    entrypoint: >
      /bin/bash -c "
      while true; do
        sleep 30 &&
        /opt/mssql-tools/bin/sqlcmd -S db -U sa -P 'YourStrongPassword!' -Q \"BACKUP DATABASE [MyDatabase] TO DISK = '/var/opt/mssql/backup/MyDatabase-$(date +%Y%m%d%H%M%S).bak'\";
      done
      "

networks:
  app_network:
    driver: bridge

volumes:
  sqlserver_data:
