apiVersion: v1
kind: PersistentVolume
metadata:
  name: dotnet-app-source-code-persisent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: dotnet-app-source-code-persisent-volume-claim
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/lab/kubernetes/kubernetes-sandbox/dotnet-db-app/mounts/app"
