apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapi
  template:
    metadata:
      labels:
        app: mywebapi
    spec:
      containers:
        - name: mywebapi
          image: mywebapi:local
          ports:
            - containerPort: 80
          env:
            - name: JwtSettings__SecretKey
              value: NewSuperSecretKey1234567890
            - name: EnvKey
              value: ProvidedValue
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapi-service
spec:
  type: NodePort
  selector:
    app: mywebapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
