@WebApiWithDb_HostAddress = http://localhost:5200

GET {{WebApiWithDb_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApiWithDb_HostAddress}}/products/
Accept: application/json

###

POST {{WebApiWithDb_HostAddress}}/products
Content-Type: application/json
Accept: application/json
{
  "name": "Sample Product",
  "age": 25
}