apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-db
spec:
  selector:
    matchLabels:
      app: dotnet-app-db
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet-app-db
    spec:
      containers:
        - name: dotnet-app-db
          image: postgres:13
          ports:
            - containerPort: 5432
              name: "postgres"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: dotnet-app-postgres-data-storage
          env:
            # Implicitly set the POSTGRES_DB, POSTGRES_USER, and POSTGRES_PASSWORD environment variables
            # - name: POSTGRES_DB
            #   value: dotnet_app_db
            # - name: POSTGRES_USER
            #   value: dotnet_app_db
            # - name: POSTGRES_PASSWORD
            #   value: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              memory: 4Gi
              cpu: "2"
      volumes:
        - name: dotnet-app-postgres-data-storage
          persistentVolumeClaim:
            claimName: dotnet-app-postgres-data-persisent-volume-claim