apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-db
spec:
  selector:
    matchLabels:
      app: dotnet-app-db
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet-app-db
    spec:
      containers:
        - name: dotnet-app-db
          image: postgres:13
          ports:
            - containerPort: 5432
              name: "postgres"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: dotnet-app-postgres-data-storage
          env:
            - name: POSTGRES_DB
              value: vehicle_quotes
            - name: POSTGRES_USER
              value: vehicle_quotes
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            limits:
              memory: 4Gi
              cpu: "2"
      volumes:
        - name: dotnet-app-postgres-data-storage
          persistentVolumeClaim:
            claimName: dotnet-app-postgres-data-persisent-volume-claim