apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-db-service
spec:
  # type: NodePort
  selector:
    app: dotnet-app-db
  ports:
    - name: "postgres"
      protocol: TCP
      port: 5432
      targetPort: 5432
      # nodePort: 30432