apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dotnet-app-postgres-data-persisent-volume-claim
spec:
  volumeName: dotnet-app-postgres-data-persisent-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi